### ISSUE TITLE
pop medial wall before multivariate zscoring?

### ISSUE THREAD

**Issue by shyu2kko** [MICA-MNI/z-brains#32]
hyperintensity on medial wall giving zscore of ~19

<img width="1074" alt="Screenshot 2023-11-29 at 4 56 46 PM" src="https://github.com/MICA-MNI/z-brains/assets/94867463/a8609812-6a86-4c46-a08b-085e3670b207">

**Comment by rcruces** [comment]
the reports are done by @rcruces
