### ISSUE TITLE
Native space feature sampling

### ISSUE THREAD

**Issue by royj23** [MICA-MNI/z-brains#8]
Should we map the surfaces to sample features in each modality's native space?

**Comment by royj23** [comment]
Friday 5pm verdict: everything goes to nativepro!

**Comment by jordandekraker** [comment]
Finally just got to reading through some of the code here!

Maybe we should just wait on this issue. Micapipe will soon output a copy of each preprocessed image in space-nativepro. If that's the case then we can skip the registration steps performed here, but we have to wait for that change to be implemented in micapipe first. Thoughts?

I'm also happy to work with the registrations as they are now, it'll just take some time to get the transforms right

**Comment by royj23** [comment]
Makes sense to me @jordandekraker! No need to double the workload. One note for FLAIR though, the nativepro transform 
could be done in z-brains, as micapipe doesn't do anything with this modality (would do this in the z-brains `proc_flair` script). 
@rcruces what's the timeline for this and anything we can help with?

**Comment by rcruces** [comment]
The final verdict:

`-proc_flair` was updated in `micapipe`, its outputs are in `nativepro` space and everything is mapped from there. The latest version of micapipe v0.2.3 solve the normalization issue in `flair` processing. There is no need to do intra-subject normalization.
